export const FOCUS_REMOTE = 'FOCUS_REMOTE';
export type FOCUS_REMOTE = typeof FOCUS_REMOTE;

export const TOGGLE_REMOTE = 'TOGGLE_REMOTE';
export type TOGGLE_REMOTE = typeof TOGGLE_REMOTE;

export const LOADED_BUTTONS = 'LOADED_BUTTONS';
export type LOADED_BUTTONS = typeof LOADED_BUTTONS;

export const LOADED_REMOTES = 'LOADED_REMOTES';
export type LOADED_REMOTES = typeof LOADED_REMOTES;

export const LOADED_ACTIVITIES = 'LOADED_ACTIVITIES';
export type LOADED_ACTIVITIES = typeof LOADED_ACTIVITIES;
